#!/bin/bash

SCRIPTDIR=$(dirname $(which "${0}"))
CONF_FILE="${SCRIPTDIR}/pbpro.conf"

if [ ! -f "${CONF_FILE}" ] ; then
    echo "A configuration file is needed."
    echo "Please edit ${CONF_FILE}"
    echo "PROTRACK_DB_URL=" > "${CONF_FILE}"
    echo "PROTRACK_DB_USER=" >> "${CONF_FILE}"
    echo "RESOURCESPACE_DB_HOST=" >> "${CONF_FILE}"
    echo "RESOURCESPACE_DB_NAME=" >> "${CONF_FILE}"
    echo "RESOURCESPACE_DB_USER=" >> "${CONF_FILE}"
    echo "RESOURCESPACE_DB_PW=" >> "${CONF_FILE}"
    exit 1
fi

. "${CONF_FILE}" || { echo "Missing ${CONF_FILE}. Exiting." ; exit 1 ;};

if [[ -z "$PROTRACK_DB_URL" || -z "$PROTRACK_DB_USER" ]] ; then
    >&2 echo "Please set info for the postgres connection in ${CONF_FILE}."
    exit 1
fi

psql -Ath "$PROTRACK_DB_URL" -U "$PROTRACK_DB_USER" -d protrack -c "\
    SELECT
        CASE WHEN pbcore_episodes_xml is not null OR pbcore_filler_xml is not null THEN
            XMLELEMENT(
                NAME \"pbcoreCollection\",
                XMLATTRIBUTES(
                    now() as \"collectionDate\",
                    'http://www.pbcore.org/PBCore/PBCoreNamespace.html' as \"xmlns\"
            ),
            pbcore_episodes_xml,
            pbcore_filler_xml)
        END
    FROM (
        SELECT
            XMLAGG(
                XMLELEMENT(
                    NAME \"pbcoreDescriptionDocument\",\
                    XMLELEMENT(
                        NAME \"pbcoreAssetType\",
                        CASE WHEN ser_type = 'P' THEN 'Program' ELSE 'Episode' END
                    ),
                    (SELECT
                        XMLELEMENT(NAME \"pbcoreAssetDate\",
                            XMLATTRIBUTES(
                                'broadcast' as \"dateType\",
                                'according to ProTrack' as \"annotation\"
                                ),
                            MIN(air.ai_air_strt_inst))
                    FROM air
                    WHERE ai_vsn_id = vsn_serial
                    ),
                    XMLELEMENT(
                        NAME \"pbcoreIdentifier\",
                        XMLATTRIBUTES('NOLA Code' as \"source\"),
                        trim(vsn_nola_code)
                    ),
                    XMLELEMENT(
                        NAME \"pbcoreIdentifier\",
                        XMLATTRIBUTES('vsn_serial' as \"source\"),
                        vsn_serial
                    ),
                    (SELECT
                    CASE WHEN ttl_text is not null THEN
                        XMLELEMENT(NAME \"pbcoreTitle\",
                            XMLATTRIBUTES(CASE WHEN ser_type = 'P' THEN 'Program' ELSE 'Series' END as \"titleType\"),
                            trim(ttl_text))
                    END
                    FROM titles as series_ac_titles
                    WHERE series_ac_titles.ttl_ser_id = quad_tab.ser_serial AND
                        series_ac_titles.ttl_prog_id = '-1' AND
                        series_ac_titles.ttl_type = 'AC'
                    ),
                    CASE WHEN ser_title is not null THEN XMLELEMENT(NAME \"pbcoreTitle\",
                        XMLATTRIBUTES(
                            CASE WHEN ser_type = 'P' THEN 'Program' ELSE 'Series' END as \"titleType\",
                            'unpreserved case' as \"annotation\"
                        ),
                        replace(initcap(trim(ser_title)),chr(39)||'S', chr(39)||'s') )
                    END,
                    (SELECT
                        XMLELEMENT(NAME \"pbcoreTitle\",
                            XMLATTRIBUTES(CASE WHEN ser_type = 'P' THEN 'Subtitle' ELSE 'Episode' END as \"titleType\"),
                            trim(ttl_text))
                    FROM titles AS episode_ac_titles
                    WHERE episode_ac_titles.ttl_prog_id = quad_tab.pg_serial AND
                        episode_ac_titles.ttl_type = 'AC'
                    ),
                    CASE WHEN pg_title is not null THEN
                        XMLELEMENT(NAME \"pbcoreTitle\",
                            XMLATTRIBUTES(
                                CASE WHEN ser_type = 'P' THEN 'Subtitle' ELSE 'Episode' END as \"titleType\",
                                'unpreserved case' as \"annotation\"
                            ),
                            initcap(trim(pg_title)) )
                    END,
                    (SELECT
                        XMLAGG(XMLELEMENT(NAME \"pbcoreDescription\",
                            XMLATTRIBUTES(trim(pgu_location) as \"descriptionType\"),
                            trim(pgu_text))
                        )
                    FROM proguide
                    WHERE pgu_vsn_id = vsn_serial
                    ),
                    (SELECT
                        CASE WHEN string_agg(pde_text,' ') is not null THEN
                            XMLELEMENT(NAME \"pbcoreDescription\",
                                XMLATTRIBUTES('Series' as \"descriptionType\"),
                                trim(string_agg(pde_text,' ' ORDER BY pde_disp_ord ASC)))
                        END
                    FROM progdesc
                    WHERE pde_ser_id = ser_serial AND pde_prog_id = '-1'
                    ),
                    (SELECT
                        CASE WHEN string_agg(pde_text,' ') is not null THEN
                            XMLELEMENT(NAME \"pbcoreDescription\",
                                XMLATTRIBUTES('Notes' as \"descriptionType\"),
                                trim(string_agg(pde_text,' ' ORDER BY pde_disp_ord ASC)))
                        END
                    FROM progdesc
                    WHERE pde_vsn_id = vsn_serial
                    ),
                    CASE WHEN vsn_descript is not null THEN
                        XMLELEMENT(NAME \"pbcoreDescription\",
                            XMLATTRIBUTES(
                                'Version' as \"descriptionType\",
                                'unpreserved case' as \"annotation\"
                            ),
                            initcap(trim(vsn_descript)) )
                    END,
                    (SELECT XMLAGG (
                        XMLELEMENT(NAME \"pbcoreInstantiation\",
                            XMLELEMENT(NAME \"instantiationIdentifier\",
                                XMLATTRIBUTES('li_serial' as \"source\"),
                                li_serial),
                            XMLELEMENT(NAME \"instantiationIdentifier\",
                                XMLATTRIBUTES('Media ID' as \"source\"),
                                trim(li_material_id)),
                            CASE WHEN li_cart_id is not null THEN
                            XMLELEMENT(NAME \"instantiationIdentifier\",
                                XMLATTRIBUTES('Cart ID' as \"source\"),
                                trim(li_cart_id))
                            END,
                            XMLELEMENT(NAME \"instantiationDate\",
                                XMLATTRIBUTES('availableStart' as \"dateType\"),
                                li_start_date),
                            XMLELEMENT(NAME \"instantiationDate\",
                                XMLATTRIBUTES(
                                    'availableEnd' as \"dateType\",
                                    ':-/' as \"annotation\"
                                ),
                                li_end_date),
                            XMLELEMENT(NAME \"instantiationLocation\"),
                            XMLELEMENT(NAME \"instantiationTimeStart\",li_in_char),
                            XMLELEMENT(NAME \"instantiationDuration\",li_length_char),
                            CASE WHEN li_use_for_air = 0 THEN
                                XMLELEMENT(NAME \"instantiationAnnotation\",
                                    XMLATTRIBUTES('accessRestriction' as \"annotationType\"),
                                    'Restricted')
                            END,
                            CASE WHEN li_cart_id is not null THEN
                                XMLELEMENT(NAME \"instantiationAnnotation\",
                                    XMLATTRIBUTES('accessRestriction' as \"annotationType\"),
                                    'Restricted')
                            END,
                            (SELECT
                                CASE WHEN string_agg(no_text,' ') is not null THEN
                                    XMLELEMENT(NAME \"instantiationAnnotation\",
                                        XMLATTRIBUTES('Technical Notes' as \"annotationType\"),
                                        trim(string_agg(no_text,' ' ORDER BY no_sequence ASC)))
                                END
                            FROM notes
                            WHERE notes.no_parent = li_serial AND notes.no_location = 'tapelink'
                            )
                        ) ORDER BY li_material_id ASC)
                    FROM linkinfo WHERE linkinfo.li_vsn_id = quad_tab.vsn_serial
                    )
                )
            ) as pbcore_episodes_xml
        FROM quad_tab
        WHERE quad_tab.vsn_serial IN (SELECT li_vsn_id FROM linkinfo WHERE li_material_id IN ($(printf "'%s'," "$@" | sed 's/,$//')))
    ) AS pbcore_episodes_result ,
    (
        SELECT
            XMLAGG(
                XMLELEMENT(NAME \"pbcoreDescriptionDocument\",
                    XMLELEMENT(NAME \"pbcoreAssetType\", 'Promo' ),
                    XMLELEMENT(NAME \"pbcoreAssetDate\",
                        XMLATTRIBUTES('catalogued' as \"dateType\"),
                        fi_date ),
                    XMLELEMENT(NAME \"pbcoreIdentifier\",
                        XMLATTRIBUTES('fi_serial' as \"source\"),
                        fi_serial ),
                    XMLELEMENT(NAME \"pbcoreTitle\",
                        XMLATTRIBUTES('Series' as \"titleType\"),
                        initcap(trim(fi_location)) ),
                    CASE WHEN fi_title is not null THEN
                        XMLELEMENT(NAME \"pbcoreTitle\",
                            XMLATTRIBUTES(
                                'Interstitial' as \"titleType\",
                                'unpreserved case' as \"annotation\"
                            ),
                            initcap(trim(fi_title))
                        )
                    END,
                    CASE WHEN fi_title2 is not null THEN
                        XMLELEMENT(NAME \"pbcoreTitle\",
                            XMLATTRIBUTES(
                                'Subtitle' as \"titleType\",
                                'unpreserved case' as \"annotation\"
                            ),
                            initcap(trim(fi_title2))
                        )
                    END,
                    CASE WHEN fi_notes is not null THEN
                        XMLELEMENT(NAME \"pbcoreDescription\",
                            XMLATTRIBUTES('Broadcast Notes' as \"descriptionType\"),
                            concat_ws(' ',trim(fi_notes),trim(fi_notes2))
                        )
                    ELSE
                        XMLELEMENT(NAME \"pbcoreDescription\")
                    END,
                    filler_notes,
                    XMLELEMENT(NAME \"pbcoreInstantiation\",
                        XMLELEMENT(NAME \"instantiationIdentifier\",
                            XMLATTRIBUTES('Media ID' as \"source\"),
                        trim(fi_video_src) ),
                        XMLELEMENT(NAME \"instantiationLocation\", '' ),
                        XMLELEMENT(NAME \"instantiationDuration\", fi_length2 ),
                        CASE WHEN fi_length != fi_length2 THEN
                            XMLELEMENT(NAME \"instantiationAnnotation\",
                                XMLATTRIBUTES('minimum duration' as \"annotationType\"),
                                fi_length
                            )
                        END
                    )
                )
            ) as pbcore_filler_xml
        FROM filler
        LEFT JOIN (
            SELECT no_parent AS fi_serial,
                XMLELEMENT(NAME \"pbcoreDescription\",
                    XMLATTRIBUTES('Abstract' as \"descriptionType\"),
                    STRING_AGG( trim(no_text), ' ' ORDER BY no_sequence ASC)
                ) as filler_notes
            FROM notes
            WHERE no_location = 'promo'
            GROUP BY fi_serial
        ) o using (fi_serial)
        WHERE fi_video_src IN ( $(printf "'%s'," "$@" | sed 's/,$//') )
    ) AS pbcore_filler_result
"
