#!/bin/bash
SCRIPTDIR="$(dirname "$0")"
CONF_FILE="${SCRIPTDIR}/pbpro.conf"
MEDIAID="${1}"

_maketemp(){
    mktemp -q "/tmp/$(basename "${0}").XXXXXX"
    if [ "${?}" -ne 0 ]; then
        echo "${0}: Can't create temp file, exiting..."
        _writeerrorlog "_maketemp" "was unable to create the temp file, so the script had to exit."
        exit 1
    fi
}

if [ ! -f "${CONF_FILE}" ] ; then
    echo "A configuration file is needed."
    echo "Please edit ${CONF_FILE}"
    echo "PROTRACK_DB_URL=" > "${CONF_FILE}"
    echo "PROTRACK_DB_USER=" >> "${CONF_FILE}"
    echo "RESOURCESPACE_DB_HOST=" >> "${CONF_FILE}"
    echo "RESOURCESPACE_DB_NAME=" >> "${CONF_FILE}"
    echo "RESOURCESPACE_DB_USER=" >> "${CONF_FILE}"
    echo "RESOURCESPACE_DB_PW=" >> "${CONF_FILE}"
    exit 1
fi

. "${CONF_FILE}" || { echo "Missing ${CONF_FILE}. Exiting." ; exit 1 ;};

TEMPXML=$(_maketemp)
TEMPPBCORE=$(_maketemp)

"${SCRIPTDIR}/pbprotracktor" "${MEDIAID}" > "${TEMPXML}"
if [ ! -s "${TEMPXML}" ] ; then
  echo "pbprotracktor did not return a result for ${MEDIAID}, exiting."
  exit 1
fi
SERIESTITLE=$(xml sel -N p="http://www.pbcore.org/PBCore/PBCoreNamespace.html" -t -v "p:pbcoreDescriptionDocument/p:pbcoreTitle[@titleType='Series'][1]" "${TEMPXML}")
if [ -n "${SERIESTITLE}" ] ; then
    COLLECTION_ID=$(mysql -BNr -h "${RESOURCESPACE_DB_HOST}" -u "${RESOURCESPACE_DB_USER}" -p"${RESOURCESPACE_DB_PW}" -D "${RESOURCESPACE_DB_NAME}" -e "SELECT ref FROM collection WHERE name = '${SERIESTITLE}' LIMIT 1 ;")
fi
if [[ -z "${COLLECTION_ID}" ]] ; then
    mysql -h "${RESOURCESPACE_DB_HOST}" -u "${RESOURCESPACE_DB_USER}" -p"${RESOURCESPACE_DB_PW}" -D "${RESOURCESPACE_DB_NAME}" -e "INSERT INTO collection  (name,public,theme,created,user,allow_changes) VALUES('${SERIESTITLE}',1,'Series',now(),3,1)" ;
    COLLECTION_ID=$(mysql -BNr -h "${RESOURCESPACE_DB_HOST}" -u "${RESOURCESPACE_DB_USER}" -p"${RESOURCESPACE_DB_PW}" -D "${RESOURCESPACE_DB_NAME}" -e "SELECT ref FROM collection WHERE name = '${SERIESTITLE}' LIMIT 1 ;")
fi
xsltproc --nonet --stringparam id "${MEDIAID}" --stringparam collectionid "${COLLECTION_ID}" "${SCRIPTDIR}/pbcore2resourcespace.xsl" "${TEMPXML}" > "${TEMPPBCORE}"
if [ -s "${TEMPXML}" ] ; then
curl --data-urlencode "xml@${TEMPPBCORE}" http://respace.cunytv.lan/plugins/remoteimport/pages/update_unsafe.php
echo
else
    echo "Metadata about $MEDIAID is unavailable."
fi
if [ -f "${TEMPXML}" ] ;then
    rm "${TEMPXML}"
fi
